
from io import StringIO

from . import write_lmp
from .. import AtomCell, Atoms


def test_write_lmp():
    cell = AtomCell(Atoms({
        'x': [0., 5., 8.],
        'y': [2., 5., 9.],
        'z': [2., 5., 9.],
        'v_x': [1., -1., 2.],
        'v_y': [2., 4., -2.],
        'v_z': [2., 2., -1.],
        'elem': [5, 1, 18],
    }), cell_size=[4., 6., 10.])

    f = StringIO()

    write_lmp(cell, f)
    s = f.getvalue()
    assert s.startswith("# Generated by structlib")
    assert s.split('\n', 1)[1] == """
        3 atoms
        3 atom types

        0.0000000      4.0000000 xlo xhi
        0.0000000      6.0000000 ylo yhi
        0.0000000     10.0000000 zlo zhi

Masses

        1      1.0080000  # H
        2     10.8100004  # B
        3     39.9500008  # Ar

Atoms  # atomic

        1    2      0.0000000      2.0000000      2.0000000
        2    1      5.0000000      5.0000000      5.0000000
        3    3      8.0000000      9.0000000      9.0000000

Velocities

        1      1.0000000      2.0000000      2.0000000
        2     -1.0000000      4.0000000      2.0000000
        3      2.0000000     -2.0000000     -1.0000000
"""