site_name: atomlib Documentation
repo_url: https://github.com/hexane360/atomlib

docs_dir: 'docs'
site_dir: 'site'
extra_css:
  - style.css

nav:
  - Home: index.md
  - 'Using atomlib':
    - using/getting_started.md
    - using/coords.md
  - API:
    - api/index.md
    - api/defect.md
    - api/transform.md
    - api/types.md
    - api/util.md

theme:
  name: material
  palette:
    primary: purple
    accent: green
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
extra:
  version:
    provider: mike
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - markdown_include.include:
      base_path: docs

plugins:
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: templates
      handlers:
        python:
          paths: [.]
          import:
            # 3rd-party object inventories
            - https://docs.python.org/3/objects.inv

            - https://numpy.org/doc/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv 
            - https://matplotlib.org/stable/objects.inv
            - https://docs.h5py.org/en/latest/objects.inv

            - https://arrow.apache.org/docs/objects.inv
            - https://pola-rs.github.io/polars/py-polars/html/objects.inv
          options:
            show_if_no_docstring: true
            show_root_heading: false
            members_order: source
            filters: ["!^_", "!^__(all|repr|str)__$", "!^(Transform3D|Num)?[TUKVP](_co(ntra)?)?$", "!^.*Self$"]
            inherited_members: true
  - mike:
      version_selector: true
      canonical_version: latest
     #alias_type: symlink

watch:
  - atomlib/
  - README.md
