site_name: atomlib Documentation
repo_url: https://github.com/hexane360/atomlib

docs_dir: 'docs'
site_dir: 'site'
extra_css:
  - style.css

nav:
  - Home: index.md
  - 'Using atomlib':
    - Getting started: using/getting_started.md
    - Coordinate systems: using/coords.md
  - API:
    - api/index.md
    - atomlib.util: api/util.md

theme:
  name: material
  palette:
    primary: purple
    accent: green
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.indexes
extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search
  - autorefs
  - mkdocstrings:
      custom_templates: templates
      handlers:
        python:
          paths: [.]
          import:
            # 3rd-party object inventories
            - https://docs.python.org/3/objects.inv

            - https://numpy.org/doc/stable/objects.inv
            - https://docs.scipy.org/doc/scipy/objects.inv 
            - https://matplotlib.org/stable/objects.inv
            - https://docs.h5py.org/en/latest/objects.inv

            - https://arrow.apache.org/docs/objects.inv
            - https://pola-rs.github.io/polars/py-polars/html/objects.inv
          options:
            show_if_no_docstring: true
            show_root_heading: true
            members_order: source
            filters: ["!^_", "!^__(all|repr|str)__$", "!^[TUKVP](_co(ntra)?)?$"]
            inherited_members: true
  - mike:
      version_selector: true
      canonical_version: latest
     #alias_type: symlink

watch:
  - atomlib/
