name: CI
on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Python ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        version: ["3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macOS-latest]
        arch: [x64]
        experimental: [false]
        #include:
        #  - version: "3.12-dev"
        #    os: ubuntu-latest
        #    arch: x64
        #    experimental: true
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}
          cache: 'pip'
          cache-dependency-path: setup.cfg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
      - name: Test
        run: pytest
  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.cfg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev]'
      - name: Type check
        uses: jakebailey/pyright-action@v1
  success:
    name: Success
    runs-on: ubuntu-latest
    needs: [test, type-check]
    steps:
      - run: exit 0
