name: Deploy documentation

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'
          cache-dependency-path: setup.cfg
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[docs]'
      - name: Build documentation
        run: |
          sphinx-build docs _build
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_build/'
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1

